apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app-config
  namespace: daaxh25-dev
  labels:
    app: python-app-tekton
    app.kubernetes.io/name: python-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
data:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "8080"
  LOG_LEVEL: "INFO"
  # Add more configuration as needed
  APP_NAME: "Python Flask App"
  APP_VERSION: "1.0.0"
