apiVersion: v1
kind: Service
metadata:
  name: python-app-tekton
  namespace: daaxh25-dev
  labels:
    app: python-app-tekton
    app.kubernetes.io/name: python-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python-app-tekton
  sessionAffinity: None
