apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: python-app-openshift
  namespace: daaxh25-dev

resources:
  - configmaps/python-app-config.yaml
  - deployments/python-app-deployment.yaml
  - services/python-app-service.yaml
  - routes/python-app-route.yaml
  - pipelines/python-app-pipeline.yaml

commonLabels:
  app.kubernetes.io/name: python-app
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: python-app-tekton
    spec:
      template:
        spec:
          containers:
          - name: python-app
            envFrom:
            - configMapRef:
                name: python-app-config
